### ISSUE TITLE
SynapseReader.mod missing?

### ISSUE THREAD

**Issue by markovg** [BlueBrain/neurodamus#3]
I notice in neurodamus/core/mod/coreneuron_modlist.txt one listed .mod file does not appear to be in the repository: SynapseReader.mod ... was this omitted by mistake, or it is no longer required?

**Comment by pramodk** [comment]
As we are supporting only SONATA via open source release, `SynapseReader.mod` is not needed/relevant anymore. In fact,  `coreneuron_modlist.txt` could be removed as well. 

We will fix that. Thanks for pointing that!

**Comment by WeinaJi** [comment]
`coreneuron_modlist.txt` has been deleted by https://github.com/BlueBrain/neurodamus/commit/f1716d9982e6aaf39e09ecbe94838de10c6346d3.
