### ISSUE TITLE
Tag nbS1-2023-v1.0 breaks version parsing in setup.py

### ISSUE THREAD

**Issue by markovg** [BlueBrain/neurodamus#4]
The git tag "nbS1-2023-v1.0" breaks the version parsing code that creates the __version__ value.

Specifically, I get the following error:

"""
The version specified ('nbS1.dev2023.devv1.0.dev3') is an invalid version, this may not work as expected with newer versions of setuptools, pip, and PyPI. Please see PEP 440 for more details.
"""

May I suggest a policy ensuring tag names conform  to PEP440
e.g. a better tag name for this release would be 2.15.2+2023nbs1

This would conform to the specification:
<public version identifier>[+<local version label>]
https://peps.python.org/pep-0440/

**Comment by pramodk** [comment]
That’s a valid point! Thanks for pointing it out.

@WeinaJi: for other projects we have been using scheme https://peps.python.org/pep-0440/#version-scheme. This is also required if we create wheels etc.

you can check the versions compliance with:

```python
>>> from pep440 import is_canonical
>>> is_canonical('your-version')
False
```

**Comment by WeinaJi** [comment]
>do you remember why we decided to create a « release » instead of just a « tag » for publication purposes?
Because Zenodo archives the repository and issues a new DOI each time we create a new release.

**Comment by pramodk** [comment]
Ok, so this was done to have a DOI for publication purposes then.

**Comment by ferdonline** [comment]
I believe this is no longer an issue since we don't use `setup.py` anymore
